# ---------- Builder ----------
    FROM oven/bun:1-alpine AS builder

    WORKDIR /app
    
    # Build arguments
    ARG NEXT_PUBLIC_FIREBASE_API_KEY
    ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
    ARG NEXT_PUBLIC_FIREBASE_APP_ID
    ARG NEXT_PUBLIC_APP_URL
    ARG NEXT_PUBLIC_MAPTILER_STYLE_ID
    ARG NEXT_PUBLIC_MAPTILER_API_KEY
    ARG POSTMARK_API_KEY
    ARG POSTMARK_SERVER_TOKEN
    
    # Expose to build environment
    ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
    ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
    ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
    ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
    ENV NEXT_PUBLIC_MAPTILER_STYLE_ID=$NEXT_PUBLIC_MAPTILER_STYLE_ID
    ENV NEXT_PUBLIC_MAPTILER_API_KEY=$NEXT_PUBLIC_MAPTILER_API_KEY
    ENV POSTMARK_API_KEY=$POSTMARK_API_KEY
    ENV POSTMARK_SERVER_TOKEN=$POSTMARK_SERVER_TOKEN
    
    # Install deps
    COPY package*.json bun.lock ./
    RUN bun install --frozen-lockfile
    
    # Copy source
    COPY . .
    
    # Build app
    RUN bun run build
    
    
    # ---------- Production ----------
    FROM oven/bun:1-alpine
    
    WORKDIR /app
    
    ENV NODE_ENV=production
    
    COPY --from=builder /app ./
    
    EXPOSE 8080
    
    CMD ["bun", "run", "start"]